import Link from "next/link";
import styles from "@/style/layout.module.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <h1 className="menu">
          <Link href="/" className={styles.home}>
            Home
          </Link>
          <Link href="/products" className={styles.product}>
            Product Page
          </Link>
        </h1>
        {children}
      </body>
    </html>
  );
}
